### ISSUE TITLE
stream directly from camera not via capturing preview

### ISSUE THREAD

**Issue by fixerivan** [luohaohaha/RTMPX#3]
would it be possible to stream directly from camera?

aka not going thru the preview at all, the preview limits fps at my device (oneplus 8T) to only 30fps even if the sensor supports up to 240fps on full hd ...

**Comment by luohaohaha** [comment]
> would it be possible to stream directly from camera?
> 
> aka not going thru the preview at all, the preview limits fps at my device (oneplus 8T) to only 30fps even if the sensor supports up to 240fps on full hd ...

You can refer to getNiceRange in CameraXImplView to see what the returned range is. Generally speaking, 60fps is supported, but I don't have much devices to test. In the case of a custom camera, you definitely need to preview to reach the high frame to get the data frame, because the raw data needs to be obtained through ImageAnalysis, my English is poor, sorry
